### PR TITLE
Update README + wireframes

### PR DESCRIPTION
**Pull request by kajalinn**

### CODE REVIEW

**Review by andressikka — APPROVED** [review]
Approval

**Review by andressikka — APPROVED** [review]
Approval

**Review by andressikka — APPROVED** [review]

**Review by andressikka — APPROVED** [review]
Approval

**Review by andressikka — APPROVED** [review]

**Review by andressikka — APPROVED** [review]

**Review by andressikka — APPROVED** [review]

**Review by andressikka — COMMENTED** [review]
Approval 100500

**Review by DmitriShibin1 — APPROVED** [review]
accepted

**Review by andressikka — APPROVED** [review]

**Review by DmitriShibin1 — APPROVED** [review]

**Comment by andressikka** [comment]
Merging Nikita's data

**Pull request merged**
